### ISSUE TITLE
mdk 4.72.10.0 编译出错

### ISSUE THREAD

**Issue by ChunfengMu** [RT-Thread-packages/mbedtls#11]
编译出现类似此等错误
application.c: error: C3906U: Malformed via file '.\build\application.__i'.
解决方法：拷贝mbedtls-port/inc/tls_config.h内容到mbedtls/include/mbedtls/config.h中

烦请下次更新README.md时增加说明。

**Comment by armink** [comment]
已修复~

具体做法是在 SCons --target 生成工程时候，自动拷贝过去
