### ISSUE TITLE
代码bug反馈

### ISSUE THREAD

**Issue by xiethon** [RT-Thread-packages/mbedtls#33]
在port/src/tls_client.c 34行代码：
#define rt_kprintf rt_kprintf("[tls]");rt_kprintf
这段代码在某些场合会有bug,如在tls_app_test.c 142-143行中的代码片段：
 for (i = 0; i < ret; i++)
            rt_kprintf("%c", tls_session->buffer[i]);
实际上这个for循环无法正常打印收到的数据。

**Comment by armink** [comment]
@Lawlieta 看一下

**Comment by Lawlieta** [comment]
感谢问题反馈，对于 TLS 中日志规范，后面会统一修改为 LOD_X 这种系统日志格式处理，将有效的避免这种日志显示问题产生

**Comment by Lawlieta** [comment]
感谢反馈，问题已修复，可以更新最新软件包测试
